import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * schema ตั้งต้นตาม SPEC.md หัวข้อ 2 และ index ตามหัวข้อ 6.1
 * เขียน SQL เองแทนการ generate เพื่อให้ตรวจทานเทียบกับ spec ได้ทีละบรรทัด
 *
 * จุดที่ตั้งใจ
 * - id เป็น GENERATED BY DEFAULT ไม่ใช่ ALWAYS มิฉะนั้น import จะระบุ id เองไม่ได้ (D10)
 * - updated_at ไม่มี DEFAULT ทั้งที่ NOT NULL เพื่อให้การลืมเซ็ตค่าพังทันที
 *   แทนที่จะถูกฐานข้อมูลกลบให้เงียบ ๆ ซึ่งจะทับกฎ D1 และ D2
 * - FK ไม่กำหนด ON DELETE จึงเป็น NO ACTION เป็นตาข่ายรองรับ D5 อีกชั้น
 *   แต่ทางหลักยังเป็น service ที่ตรวจแล้วตอบ 409 DEPARTMENT_IN_USE เอง
 */
export class Init1789344000000 implements MigrationInterface {
  name = 'Init1789344000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "departments" (
        "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" VARCHAR(100) NOT NULL,
        CONSTRAINT "UQ_departments_name" UNIQUE ("name")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "employees" (
        "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name"          VARCHAR(255)  NOT NULL,
        "department_id" INT           NOT NULL,
        "salary"        DECIMAL(12,2) NOT NULL,
        "join_date"     DATE          NOT NULL,
        "is_active"     BOOLEAN       NOT NULL DEFAULT true,
        "updated_at"    TIMESTAMPTZ   NOT NULL,
        CONSTRAINT "FK_employees_department"
          FOREIGN KEY ("department_id") REFERENCES "departments" ("id")
      )
    `);

    await queryRunner.query(
      `CREATE INDEX "IDX_employees_department_id" ON "employees" ("department_id")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_employees_is_active" ON "employees" ("is_active")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_employees_join_date" ON "employees" ("join_date")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_employees_salary" ON "employees" ("salary")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_employees_lower_name" ON "employees" (lower("name"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "employees"`);
    await queryRunner.query(`DROP TABLE "departments"`);
  }
}
